"use client";
import { ThemeProvider } from "@mui/material";
import "./globals.css";
import { theme } from "./theme";
import Head from "next/head";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <>
      <html lang="en">
        <ThemeProvider theme={theme}>
          {/* <Head>
            <link rel="preconnect" href="https://fonts.googleapis.com" />
            <link rel="preconnect" href="https://fonts.gstatic.com" />
            <link
              href="https://fonts.googleapis.com/css2?family=Bakbak+One&display=swap"
              rel="stylesheet"
            />
          </Head> */}
          <body>{children}</body>
        </ThemeProvider>
      </html>
    </>
  );
}
